export class CreateUsuarioDto {
    // @PrimaryGeneratedColumn()
    // id: number;    // AUTOGENERATED NÃO APARECE AQ

    // @Column({ type: "varchar", length: 120 })
    nome: string;

    // @Column({ type: "varchar", length: 90 })
    email: string;

    // @Column({ type: "tinyint", unsigned: true })
    idade: number;

    // @Column({ type: 'varchar', length: 2 })
    nacionalidade: string;

    // @Column({ type: 'varchar', length: 50 })
    profissao: string;

}
